server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
        routes:
          - id: user-service
            uri: lb://user-service
            predicates:
              - Path=/user-service/api/users/**
            filters:
              - RewritePath=/user-service/api/users/(?<remaining>.*), /api/users/${remaining}
          - id: order-service
            uri: lb://order-service
            predicates:
              - Path=/order-service/api/orders/**
            filters:
              - RewritePath=/order-service/api/orders/(?<remaining>.*), /api/orders/${remaining}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
